/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2f3035",
        "on-surface": "#e3e2e8",
        "error": "#ffb4ab",
        "surface-tint": "#89ceff",
        "primary-fixed": "#c9e6ff",
        "surface-container-low": "#1a1b20",
        "surface-container-highest": "#343439",
        "outline": "#88929b",
        "on-background": "#e3e2e8",
        "secondary": "#d0bcff",
        "surface-bright": "#38393e",
        "surface-container-lowest": "#0d0e12",
        "tertiary": "#4fdbc8",
        "outline-variant": "#3e4850",
        "on-primary-fixed": "#001e2f",
        "on-error": "#690005",
        "error-container": "#93000a",
        "inverse-primary": "#006591",
        "surface-container-high": "#292a2e",
        "on-primary-fixed-variant": "#004c6e",
        "on-secondary-fixed-variant": "#5516be",
        "tertiary-container": "#00ae9d",
        "primary-container": "#0ea5e9",
        "on-primary-container": "#003751",
        "surface-dim": "#121317",
        "on-tertiary": "#003731",
        "on-tertiary-container": "#003a33",
        "background": "#121317",
        "secondary-fixed-dim": "#d0bcff",
        "surface-container": "#1f1f24",
        "secondary-container": "#571bc1",
        "primary": "#89ceff",
        "on-tertiary-fixed": "#00201c",
        "on-primary": "#00344d",
        "inverse-surface": "#e3e2e8",
        "on-secondary-fixed": "#23005c",
        "on-tertiary-fixed-variant": "#005048",
        "primary-fixed-dim": "#89ceff",
        "on-surface-variant": "#bec8d2",
        "tertiary-fixed-dim": "#4fdbc8",
        "on-secondary": "#3c0091",
        "on-secondary-container": "#c4abff",
        "on-error-container": "#ffdad6",
        "surface": "#121317",
        "tertiary-fixed": "#71f8e4",
        "surface-variant": "#343439",
        "secondary-fixed": "#e9ddff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "unit": "4px",
        "margin-x": "40px",
        "section-gap": "120px",
        "stack-lg": "48px",
        "container-max": "1440px",
        "stack-sm": "12px",
        "stack-md": "24px"
      },
      fontFamily: {
        'grotesk': ['Space Grotesk', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['3.5rem', '1.1'],
        'display-md': ['2.8rem', '1.2'],
        'title-lg': ['2rem', '1.5'],
        'title-md': ['1.6rem', '1.5'],
        'label-lg': ['0.875rem', '1.5'],
      }
    },
  },
  plugins: [],
}
